development:
  adapter: sqlite3
  database: db/development.db

test:
  adapter: sqlite3
  database: db/test.db

production:
  adapter: mysql2
  encoding: utf8
  database: rubyiot_server
  username: rubyiot
  password: <%= ENV['RUBYIOT_SERVER_DATABASE_PASSWORD'] %>
  host: 127.0.0.1
